### ISSUE TITLE
Dependency not listed: PyQt5

### ISSUE THREAD

**Issue by johannes-pi** [0815nutzer/OrderListTool#1]
When I want to install the main.py file, this error is generated:

```
Traceback (most recent call last):
  File "OrderListTool/main.py", line 21, in <module>
    from PyQt5.QtWidgets import (
ModuleNotFoundError: No module named 'PyQt5'
```
I think, it would be good to list this dependency in the Readme or documentation.

**Comment by johannes-pi** [comment]
The missing dependency is called:
`python3-pyqt5`

**Comment by 0815nutzer** [comment]
I've added the dependency in ReadMe.md and also in (german) documentation

**Comment by johannes-pi** [comment]
Thank you!
